In [137]:
import numpy as np
from io import StringIO

In [138]:
csv_data = \
            '''
            A,B,C,D
            1.0, 2.0, 3.0, 4.0
            5.0, 6.0,,8.0
            10.0,11.0,12.0
            '''

In [139]:
import pandas as pd

In [140]:
df =pd.read_csv(StringIO(csv_data))

In [141]:
df

A     B     C    D
0            1.0   2.0   3.0  4.0
1            5.0   6.0   NaN  8.0
2           10.0  11.0  12.0  NaN

In [142]:
# Number of missing values in each feature column
df.isnull().sum()

            A    0
B                0
C                1
D                1
dtype: int64

In [143]:
df.values
print(type(df.values))

<class 'numpy.ndarray'>


###### One of the most simplest echnique is to remove the orw or colum with tha tcontaisn missing data

In [144]:
# drop rows
df.dropna(axis=0)

A    B    C    D
0            1.0  2.0  3.0  4.0

In [145]:
# drop columns
df.dropna(axis=1)

A     B
0            1.0   2.0
1            5.0   6.0
2           10.0  11.0

dropna , method has other several parameters, such as ,
 1. only drop rows where all columsna re NAN

In [146]:
df.dropna(how='all') # no colum has alll NAN values

A     B     C    D
0            1.0   2.0   3.0  4.0
1            5.0   6.0   NaN  8.0
2           10.0  11.0  12.0  NaN

In [147]:
# drop rows that has less tha 4 real values

df.dropna(thresh=4) # row 1 and 2 has only 3 real values, so dropped

A    B    C    D
0            1.0  2.0  3.0  4.0

In [148]:
# onlt drop rows where NAN apperas in the spicific Column

df.dropna(subset=['C']) # NAN appears in 1 row in C column


A     B     C    D
0            1.0   2.0   3.0  4.0
2           10.0  11.0  12.0  NaN

#### Imputing Missing values

In [149]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

In [150]:
imr = SimpleImputer(missing_values= np.NaN, strategy='mean')

In [151]:
imr = imr.fit(df.values)

In [152]:
imputed_data = imr.transform(df.values)

In [153]:
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [154]:
# we can also other otehr oaramets liek median, mode

#### Scikit Learn Estimator API

fit - learn the parameter from training data 

transform - uses those learned paramters to trasform the data.

## Handling Categorical Data

###### Nominal and Ordinal features 
 1. Ordinal - thoese featurs that can be sored e.g. T shirt Size XL > L > M > S
 2. Nominal - that cannot be sorted e.g. T shirt Color , red, greeen,

In [155]:
import pandas as pd

In [156]:
df= pd.DataFrame([
    ['greeen', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1']
])

df.columns = ['color', 'size','price', 'classlabel']


In [157]:
df

color size  price classlabel
0  greeen    M   10.1     class1
1     red    L   13.5     class2
2    blue   XL   15.3     class1

###### Mapping Ordinal Features

e.g 
XL = L +1 = M+2

In [158]:
size_mapping = {
    'XL':3,
    'L':2,
    'M':1
}

In [159]:
df['size'] = df['size'].map(size_mapping)

In [160]:
df

color  size  price classlabel
0  greeen     1   10.1     class1
1     red     2   13.5     class2
2    blue     3   15.3     class1

#### Encoding the Class labels

In [161]:
import numpy as np

In [162]:
df

color  size  price classlabel
0  greeen     1   10.1     class1
1     red     2   13.5     class2
2    blue     3   15.3     class1

In [163]:
class_mapping = {label:idx for idx, label in enumerate(np.unique(df['classlabel']))}


In [164]:
class_mapping

{'class1': 0, 'class2': 1}

In [165]:
df['classlabel'] =df['classlabel'].map(class_mapping)

In [166]:
df

color  size  price  classlabel
0  greeen     1   10.1           0
1     red     2   13.5           1
2    blue     3   15.3           0

Scikit leanr Labe lEncoder can also be used here

In [167]:
from sklearn.preprocessing import LabelEncoder

In [168]:
class_le = LabelEncoder()


In [169]:
y = class_le.fit_transform(df['classlabel'].values)

In [170]:
X = df.values
X

array([['greeen', 1, 10.1, 0],
       ['red', 2, 13.5, 1],
       ['blue', 3, 15.3, 0]], dtype=object)

#### Performing one Hot Encoding in Nominal Feaures

In [171]:
from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer

In [172]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'),[0])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)


In [173]:
X = ct.fit_transform(X)

In [174]:
X

array([[0.0, 1.0, 0.0, 1, 10.1, 0],
       [0.0, 0.0, 1.0, 2, 13.5, 1],
       [1.0, 0.0, 0.0, 3, 15.3, 0]], dtype=object)

green -> (0 1 0)

red -> (0 0 1)

blue -> (1 0 0)

In [175]:
# can also use pandas get_dummies

In [177]:
pd.get_dummies(df[['price', 'color', 'size']])


price  size  color_blue  color_greeen  color_red
0   10.1     1           0             1          0
1   13.5     2           0             0          1
2   15.3     3           1             0          0

## Partitioning data in train - test

In [178]:
import pandas as pd

In [180]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/''ml/machine-learning-databases/''wine/wine.data', header=None)

In [185]:
df_wine.columns =['Class label', 'Alcohol', 'Malic acid', 'Ash',
                 'Alcalinity of ash',
                  'Magnesium',
                  'Total phenols', 'Flavanoids',
                  'Nonflavanoid phenols',
                  'Proanthocyanins',
                  'Color intensity', 'Hue',
                  'OD280/OD315 of diluted wines',
                  'Proline'
                 ]

In [186]:
df_wine

Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0              1    14.23        1.71  2.43               15.6        127   
1              1    13.20        1.78  2.14               11.2        100   
2              1    13.16        2.36  2.67               18.6        101   
3              1    14.37        1.95  2.50               16.8        113   
4              1    13.24        2.59  2.87               21.0        118   
..           ...      ...         ...   ...                ...        ...   
173            3    13.71        5.65  2.45               20.5         95   
174            3    13.40        3.91  2.48               23.0        102   
175            3    13.27        4.28  2.26               20.0        120   
176            3    13.17        2.59  2.37               20.0        120   
177            3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

In [187]:
np.unique(df_wine['Class label'])

array([1, 2, 3])

In [188]:
from sklearn.model_selection import train_test_split


In [225]:
X ,y = df_wine.iloc[:,1:].values, df_wine.iloc[:, 0].values


In [226]:
X_train,X_test, y_train, y_test = train_test_split(X, y , test_size =0.3, random_state =0, stratify =y)

In [227]:
X_test

array([[1.377e+01, 1.900e+00, 2.680e+00, 1.710e+01, 1.150e+02, 3.000e+00,
        2.790e+00, 3.900e-01, 1.680e+00, 6.300e+00, 1.130e+00, 2.930e+00,
        1.375e+03],
       [1.217e+01, 1.450e+00, 2.530e+00, 1.900e+01, 1.040e+02, 1.890e+00,
        1.750e+00, 4.500e-01, 1.030e+00, 2.950e+00, 1.450e+00, 2.230e+00,
        3.550e+02],
       [1.439e+01, 1.870e+00, 2.450e+00, 1.460e+01, 9.600e+01, 2.500e+00,
        2.520e+00, 3.000e-01, 1.980e+00, 5.250e+00, 1.020e+00, 3.580e+00,
        1.290e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.237e+01, 1.070e+00, 2.100e+00, 1.850e+01, 8.800e+01, 3.520e+00,
        3.750e+00, 2.400e-01, 1.950e+00, 4.500e+00, 1.040e+00, 2.770e+00,
        6.600e+02],
       [1.245e+01, 3.030e+00, 2.640e+00, 2.700e+01, 9.700e+01, 1.900e+00,
        5.800e-01, 6.300e-01, 1.140e+00, 7.500e+00, 6.700e-01, 1.730e+00,
        8.80

### Bringing Features into the same scales

#### Normaizlation - in reange of (0, 1)

In [228]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()



In [229]:
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

#### Standarization - mean -0 ,  Var -1

In [230]:
from sklearn.preprocessing import StandardScaler


In [231]:
stdsc = StandardScaler()

In [233]:
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)